version: '3'

services:
  web:
    build: api/
    command: flask run -h 0.0.0.0
    ports:
      - 5000:5000
    env_file:
      - api/.env
    depends_on:
      - db
  db:
    image: postgres:13.1
    env_file:
      - .env-postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
