version: '3.9'

services:
  api:
    build: api/
    command: flask run -h 0.0.0.0
    ports:
      - 5000:5000
    env_file:
      - api/.env
    volumes:
      - ./api/:/api/
    depends_on:
      - db
        
  db:
    image: postgres:13.1
    ports:
      - 5433:5432
    env_file:
      - .env-postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data 

  client:
    build: client/
    command: npm start
    ports:
      - 3000:3000
    stdin_open: true
    volumes:
      - ./client/:/client/

volumes:
  postgres_data:
